name:                recordscript
version:             0.1.0.0
github:              "agrafix/recordscript"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "mail@athiemann.net"
copyright:           "2018 Alexander Thiemann <mail@athiemann.net>"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A new language for the web
category:            Compiler

description:         Please see the README on GitHub at <https://github.com/agrafix/recordscript#readme>

ghc-options: -Wall -Werror

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - unordered-containers
  - hashable
  - mtl
  - transformers
  - syb >=0.4
  - megaparsec
  - scientific
  - language-javascript

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators


library:
  source-dirs: src

executables:
  recordscript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recordscript

benchmarks:
  recordscript-compare:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - recordscript
      - directory
      - aeson
      - yaml
      - filepath
      - temporary
      - typed-process

tests:
  recordscript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - recordscript
      - hspec
      - directory
      - filepath
      - temporary
      - typed-process
      - bytestring
      - yaml
      - aeson
